### PR TITLE
respect the environment variable of proxy setting

### PR DESCRIPTION
**Pull request by kkdd**
I would like osmosis to respect the environment variable of proxy setting:

```
http_proxy="http://USER:PASSWORD@HOST:PORT"
```

### CODE REVIEW

**Comment by kkdd** [comment]
I would also like the downloader for Gradle to respect the environment variable:
```
https_proxy="http://USER:PASSWORD@HOST:PORT"
```

**Comment by brettch** [comment]
This post provides some guidance on how to get gradle working behind a proxy by adding proxy information to the file USER_HOME/.gradle/gradle.properties
http://stackoverflow.com/questions/8938994/gradlew-behind-a-proxy

Re the pull request itself, a couple of questions:
* The code appears to be duplicated in two separate locations.  Is that intentional?
* This code is making global JVM changes in individual tasks which isn't ideal.  This sounds like something that should be done in the Osmosis class during startup.  Is there any reason this has to be done in individual tasks?

**Comment by kkdd** [comment]
I agree that this is a dirty patch. More ideal solution will be preferable.

**Comment by icemagno** [comment]
I'm facing some serious proxy problems with some proxies. Please see http://gis.stackexchange.com/questions/203905/how-to-setting-proxy-for-osmosis

**Comment by brettch** [comment]
I don't want to merge this in its current form, so closing for now.

**Pull request closed without merging**
