### PR TITLE
Add support for historical information

### PR DESCRIPTION
**Pull request by rtroilo**
This pull request add support for historical information and the visible attribute.

It is similar to #37 but incorporates the visible flag into CommonEntityData, as it is part of common data.
The flag is accessible through Entity.isVisible().

The visible flag indicates if this version/change was an deletion or not and is available at least since v0.3.
https://wiki.openstreetmap.org/wiki/API_v0.3.
For working with the osm historical information it is essential to have access to this flag.

### CODE REVIEW

**Comment by rtroilo** [comment]
Travis complain about not correct file endings in osmosis-apidb!
Please take a look into that.

**Comment by rtroilo** [comment]
sorry for the spamming commits, but finally travis/checkstyle is happy.

**Comment by aleung** [comment]
@rtroilo I just need the HistoricalInformation feature and found your PR. Appreciate if this PR will get merged.

**Comment by brettch** [comment]
This is a change with similar intent to #37 although it's much more complete.

Is it essential to add a `visible` flag to all entities, or can the existing change streams be used instead?

My general preference to date has been to make tasks specific to a single purpose so I'm wondering if it makes more sense to create new tasks that can read files with visible flags and pass them through the existing changes streams (using modify/delete actions to represent visible).

**Comment by brettch** [comment]
Similar to my recent closing of #37, I'm closing this one based on it not aligning to the current Osmosis design and no discussion having occurred in almost two years.

**Pull request closed without merging**
