### PR TITLE
Add constructor for osmosis-pbf2 relying directly on InputStream

### PR DESCRIPTION
**Pull request by guillaumerose**
I rewrote the PR https://github.com/openstreetmap/osmosis/pull/30 using Supplier<InputStream>

### CODE REVIEW

**Comment by guillaumerose** [comment]
Travis fails to compile with Java 7. What's your plan to switch to Java 8 ?

**Comment by brettch** [comment]
Oops, I forgot about Travis enforcing Java 7.  I guess I need a plan to upgrade now ;-)  I'll take a look at it, it might take me a day or two though.  I think I just need to update the docker config to depend on a Java 8 image instead of Java 7.

**Comment by guillaumerose** [comment]
Would you like a PR ? I suppose I just have to change the Dockerfile and build.gradle.

**Comment by brettch** [comment]
A PR would be great.  I'll get to it eventually if you don't ;-)  Just been a bit busy this past week.

**Comment by brettch** [comment]
We got there eventually :-)  Thanks for the patch.

**Pull request merged**
