### PR TITLE
Fix query for retrieving relation members and preventing duplicate WayNodes in Ways

### PR DESCRIPTION
**Pull request by jeffreyerikson**
A couple more fixes as we've further used the pgsnapshot module.  The first fix changes the name of the field used for the relation ID in the SQL statement since PostgreSQL doesn't like aliased fields being used in the query criteria.  

The second fix prevents way nodes from being duplicated when a Way is retrieved.  We were seeing the proper WayNodes being added to the list, then fetched again and tacked on to the end of the list.

I'm not sure if there would ever be a case where the nodes would not be returned when the Way is initially loaded by the call to super.getEntity() in WayDao.java, so I've added a check to see if the node list is already populated before trying to populate it again.  There very well may be a better way to handle this, but this logic prevents duplicate nodes from appearing given our use-case.

Note, I don't seem to be able to run the test suite here . . . failing tests in the apidb module.  Is there any documentation for setting up an environment for testing?

Thanks!

### CODE REVIEW

**Comment by brettch** [comment]
Thanks.  I'll take a look as soon as I can.

As for running tests, are you able to use Docker?  In the db-server directory there's scripts for building and running a Docker container with all database pre-requisites and schemas installed.  There's a readme in that directory with (limited) instructions.  That's how I do my testing now.  It's much easier than manually setting up a database server, and should give more consistent results.

Given that you've only modified the pgsnapshot codebase, you can run "../gradlew build" from the osmosis-pgsnapshot directory.  That will just run the tests in that project.

**Comment by jeffreyerikson** [comment]
Thanks for the pointers to the Docker setup . . . great way to set up a test environment!  I've run the pgsnapshot module tests locally and they pass.

**Comment by brettch** [comment]
Sorry this took so long.  It took me a while to find time to figure out how this bit of code worked again :-)  I was a bit confused what was causing it, and why relations didn't have the same issue.  I forgot that the way table embeds the list of node ids in it.  Oops.

Based on that, I think the nodes will always be populated so the whole loadFeatures method should be able to be deleted.  Unfortunately, I don't think any tests exercise this bit of functionality.  I'll remove it and hope for the best.

**Comment by jeffreyerikson** [comment]
Sounds good.  While nothing replaces tests, if it helps any, we've been
running with this fix for a few weeks here and haven't run into any issues.

Thanks for all your work on this . . . we're really grateful Osmosis is
available!

je

**Pull request merged**
