### PR TITLE
Update for protobuf 3.11.4.

### PR DESCRIPTION
**Pull request by sebastic**
The protobuf package in Debian has recently been updated to version 3.11.4 which causes the osmosis package build to fail, as reported by Pirate Praveen in [Debian Bug #944928](https://bugs.debian.org/944928).

The java files were regenerated with `osmosis-osm-binary/osmosis-protoc.sh` after the `optimize_for` option was disabled in the `.proto` files due to this change:
>  * Make Java protoc code generator ignore optimize_for LITE_RUNTIME. Users should instead use the Java lite protoc plugin.`

### CODE REVIEW

**Comment by migurski** [comment]
Thanks Bas! Would you mind adding a small test to the suite for your changes?

**Comment by sebastic** [comment]
My Java-fu is pretty basic, so I don't think I can.

**Comment by migurski** [comment]
Okay, since this all looks auto-generated I’ll go ahead and merge. Thanks for your help!

**Comment by sebastic** [comment]
Yes, and ideally this would be auto-generated during the build like [osmpbf](https://github.com/openstreetmap/OSM-binary/blob/master/build.xml#L21) does.

**Pull request merged**
